import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import axios from "axios";
import Link from "next/link";
// import { getBlockchain } from "../ethereum";
import getBlockchain from "../ethereum.js";

import { useEffect, useState } from "react";

export const Container = styled.div`
  display: flex;
  /* justify-content: center; */
  flex-direction: row;
  flex-wrap: wrap;
`;

export const Card = styled.div`
  min-width: 100px;
  min-height: 100px;
  background-color: #f9f9f9;
  border-radius: 10px;
  margin: 10px;

  display: flex;
  justify-content: center;
  align-items: center;
`;

export const ExteriorCard = styled.div`
  min-width: 320px;
  min-height: 100px;
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  margin: 10px;
  border: 1.2px solid rgba(0, 0, 0, 0.1);

  display: flex;
  /* justify-content: center; */
  align-items: center;
`;

export const P = styled.p`
  background-color: black;
  max-width: fit-content;
  font-family: monospace;
  margin-left: 5px;
  padding: 2px;
  border-radius: 1px;
  padding: 3px;
`;

export default function Home() {
  const [data, setData] = useState([]);
  const [token, setToken] = useState();
  const [account, setAccount] = useState("");
  const [info, setInfo] = useState([]);

  useEffect(() => {
    const init = async () => {
      // if (nft) {
      //   console.log("there is");
      // } else {
      //   console.log("there is not");
      // }
      const { nft } = await getBlockchain();
      setToken(nft);
      const balance = await nft.balanceOf(
        nft.provider.provider.selectedAddress
      );
      console.log(`balance ${balance}`);

      console.log(nft.provider.provider.selectedAddress);
      setAccount(nft.provider.provider.selectedAddress);

      const acc = nft.provider.provider.selectedAddress;
      for (let i = 0; i < balance; i++) {
        const item = await nft.getNfts(acc, i);
        let date = new Date(Number(item.date) * 1000);

        const obj = {
          name: item.name,
          image: item.imageUrl,
          date: item.date,
          owner: item.owner,
        };

        setInfo((info) => [...info, obj]);

        // const data = await axios.get(tokenURI);
        // const name = await data.data.title;
        // const picture = await data.data.properties.image.description;
        // console.log(data);
        // setInfo((info) => [...info, { picture, name }]);
      }
    };
    init();
  }, []);

  return (
    <>
      {/* {console.log(info)} */}
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
          {info.map((item, key) => {
            return (
              <ExteriorCard key={key}>
                <Card>
                  <img src={item.image} width="100px" alt="" />
                </Card>
                <div>
                  <P>Name: {item.name}</P>
                  <P>price: 0.01 eth</P>
                  <P>Owner: {item.owner}</P>
                </div>
              </ExteriorCard>
            );
          })}

          {/* <ExteriorCard>
            <Card>
              <img src="http://localhost:3000/two.png" width="80px" alt="" />
            </Card>
            <div>
              <P>Name:</P>
              <P>price:</P>
              <P>Owner:</P>
            </div>
          </ExteriorCard> */}
        </Container>
      </div>
    </>
  );
}
