import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import axios from "axios";
import Link from "next/link";
// import { getBlockchain } from "../ethereum";
import getBlockchain from "../ethereum.js";

import { useEffect, useState } from "react";

export const Container = styled.div`
  display: flex;
  /* justify-content: center; */
  flex-direction: row;
  flex-wrap: wrap;
`;

export const Card = styled.div`
  min-width: 100px;
  min-height: 100px;
  background-color: #f9f9f9;
  border-radius: 10px;
  margin: 10px;

  display: flex;
  justify-content: center;
  align-items: center;
`;

export const ExteriorCard = styled.div`
  min-width: 320px;
  min-height: 100px;
  background-color: rgba(255, 255, 255, 0.5);
  border-radius: 10px;
  margin: 10px;
  border: 1.2px solid rgba(0, 0, 0, 0.1);

  display: flex;
  /* justify-content: center; */
  align-items: center;
`;

export const P = styled.p`
  /* word-wrap: break-word; */
  background-color: black;
  font-family: monospace;
  margin-left: 5px;
  padding: 2px;
`;

export default function Home() {
  const [data, setData] = useState([]);
  // const [nft, setNft] = useState();

  useEffect(() => {
    const init = async () => {
      const { nft } = await getBlockchain();
      // const balance = await nft.balanceOf(
      //   nft.provider.provider.selectedAddress
      // );

      // setTokenInfo(nft);

      // console.log(nft.provider.provider.selectedAddress);
      // console.log(nft.provider);

      // console.log(`balance: ${balance}`);

      // for (let i = 0; i < balance; i++) {
      //   let tokenURI = await nft.tokenURI(i);
      //   const data = await axios.get(tokenURI);
      //   const name = await data.data.title;
      //   const picture = await data.data.properties.image.description;
      //   console.log(data);
      //   setImages((images) => [...images, { picture, name }]);
      // }
    };
    init();
  }, []);

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
          <ExteriorCard>
            <Card>
              <img src="./one.png" width="100px" alt="" />
            </Card>
            <div>
              <P>Name</P>
              <P>price</P>
              <P>amount</P>
            </div>
          </ExteriorCard>
          <ExteriorCard>
            <Card>
              <img src="./two.png" width="80px" alt="" />
            </Card>
            <div>
              <P>Name</P>
              <P>price</P>
              <P>amount</P>
            </div>
          </ExteriorCard>
        </Container>
      </div>
    </>
  );
}
